/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ['image/webp', 'image/avif'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1400, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384, 512, 640, 750, 828, 1080, 1200, 1400],
  },
  async rewrites() {
    return [
      // 1. Direct Blog route accesses
      {
        source: '/blog',
        destination: 'https://cimulink-blog.vercel.app/',
      },
      // 2. All deep-linked blog paths and assets properly referenced under /blog/
      {
        source: '/blog/:path*',
        destination: 'https://cimulink-blog.vercel.app/:path*',
      },
      // 3. Catch-all for relative asset requests generated by Quartz when /blog is visited without a trailing slash.
      // This automatically forwards any CSS, JS, JSON, etc. to the blog if the request originated from a /blog page.
      {
        source: '/:path+',
        has: [
          {
            type: 'header',
            key: 'referer',
            value: '.*\/blog.*',
          },
        ],
        destination: 'https://cimulink-blog.vercel.app/:path+',
      },
    ]
  },
}

module.exports = nextConfig